### PR TITLE
Fixes #1610 InstanceURl edit preference added in settings

### LINKED ISSUE #1610: No option for user to change instance url when signed in
**Summary:** 

Once any user has signed in the app. He/she cannot change the instance url. Although there should be a way to do so without resigning and reconfiguring the network setting.

**Expected behaviour:** 

In settings there should be option for changing the instance url.

**Observed behaviour:** 

No option in the app for changing instance url after signing in.

**Device and Android version:** 

* ANY

### PR DESCRIPTION
**Pull request by danishjamal104**
Fixes #1610  

ss-2 | ss-1

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by danishjamal104** [comment]
@robustTechie please review the changes. thanks :)

**Comment by robustTechie** [comment]
Hey, @danishjamal104 how about adding the passcode verification just before changing the Instance URL ?

**Review by robustTechie — COMMENTED** [review]
Hey, @danishjamal104 how about adding the passcode verification just before changing the Instance URL ?

**Comment by danishjamal104** [comment]
> Hey, @danishjamal104 how about adding the passcode verification just before changing the Instance URL ?

I am not able to get the actual idea of how things are related. Like what's the difference between domain and instance and the changes that I made only updates the sharedPref using Prefmanager as you can. see in changes. I wasn't clear about it that's why I didn't applied passcode functionality.
So please help me with that.

**Comment by robustTechie** [comment]
Yeah, so you can something like if the user clicks on change instance thing then it will ask the user to enter the passcode then allows to change the URL

**Review by iamsh4shank — APPROVED** [review]

**Comment by iamsh4shank** [comment]
@danishjamal104 any update on this?

**Comment by danishjamal104** [comment]
> @danishjamal104 any update on this?

I think passcode isn't required while changing the instance URL, because its more of a administration thing, and while starting the app also user has option to change the domain, port, and tenant which is before setting password.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsFragment.kt [hunk 1]
```diff
@@ -54,6 +49,28 @@ class SettingsFragment : PreferenceFragment(), SharedPreferences.OnSharedPrefere
             true
         }
 
+        mInstanceUrlPref = findPreference(
+                getString(R.string.hint_instance_url)) as EditTextPreference
+        val instanceUrl = PrefManager.getInstanceUrl()
+        mInstanceUrlPref!!.text = instanceUrl
+        mInstanceUrlPref!!.isSelectable = true
+        mInstanceUrlPref!!.dialogTitle = "Edit Instance Url"
```
Comment (iamsh4shank) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsFragment.kt:57]: It would be great if you could change this hardcoded string into string resources :)

**Review by iamsh4shank — CHANGES_REQUESTED** [review]

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Hwy @danishjamal104 can you fix the requested changes as well as merge conflicts so that we could merge it soon :)

**Review by iamsh4shank — APPROVED** [review]
