### PR TITLE
Restore the language set before logging out

### LINKED ISSUE #1922: The language returns to English once we logout
**Summary:** 

After changing the language in settings and logging out, the language is reset back to english.

**Steps to reproduce:** 

https://user-images.githubusercontent.com/94394661/227757254-cc2c8271-1bf5-483c-8516-2ccdc28ff3fb.mp4

**Device and Android version:** 

Device : OnePlus Nord
Android 12

### PR DESCRIPTION
**Pull request by Aditya-gupta99**
Fixes #1922 

https://user-images.githubusercontent.com/94394661/227764311-37902dc6-cd1e-4359-8288-35eee61ae05e.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Aditya-gupta99** [comment]
@avinash14022002 Can you please review this PR

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsActivity.kt [hunk 1]
```diff
@@ -2,26 +2,39 @@ package com.mifos.mifosxdroid
...
 import com.mifos.mifosxdroid.core.MifosBaseActivity
 import com.mifos.mifosxdroid.online.DashboardActivity
+import com.mifos.utils.Constants
 
 /**
  * Created by mayankjindal on 22/07/17.
  */
 class SettingsActivity : MifosBaseActivity() {
+
+    private var hasSettingsChanged = false
```
Comment (avinash14022002) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsActivity.kt:15]: if its regarding language setting then please use appropriate variable naming

**Review by avinash14022002 — APPROVED** [review]
LGTM
