### PR TITLE
Fix: resolved identifier issues

### LINKED ISSUE #768: Issues in client identifiers
**Summary:** 

There are 3 issues in client identifiers which need to be resolved.
1. This is already reported. Please see #648 
2. If there is only one item in identifier list, then it is visible even after removing it. Please see the GIF -
issue2

3. If there is no item in identifier list, then the message is shown that "There is no identifier to show". But this error is visible even after a new identifier is added. Please see the GIF - 
issue3   

**Steps to reproduce:** 

Open the app
Go to Navbar and select Clients
Select Client
From the Toolbar menu select Identifiers

### PR DESCRIPTION
**Pull request by mayank-kgp**
Resolves #768 #648 (duplicate of #768)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java [hunk 1]
```diff
@@ -128,6 +128,9 @@ public void showUserInterface() {
 
     @Override
     public void showClientIdentifiers(List<Identifier> identifiers) {
+        if (ll_error.getVisibility() == View.VISIBLE) {
```
Comment (therajanmaurya) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: Make variable name `ll_error` to `llError`.

**Comment by mayank-kgp** [comment]
@therajanmaurya Changes made.
