### PR TITLE
Fix #937:Hiding keyboard on button press

### LINKED ISSUE #937: Hiding keyboard/Putting Toast inside the dialog in Identifiers
**Summary:** 

When Create identifier button is pressed and the keyboard is still on the screen the toast message for the error hides behind the dialog and the keyboard and is not visible to the user.

**Steps to reproduce:** 

1) Run the app
2) Select Client
3) Identifiers
4) create an identifier

**Screenshots:**

### PR DESCRIPTION
**Pull request by AkshGautam**
Please make sure these boxes are checked before submitting your pull request - thanks!
fix #937
@therajanmaurya Please review
- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java [hunk 1]
```diff
@@ -47,6 +48,9 @@
     @BindView(R.id.et_description)
     EditText et_description;
 
+    @BindView(R.id.btn_create_identifier)
+    Button btn_identifier;
```
Comment (therajanmaurya) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java]: @AkshGautam Please use camel case naming convention and change the other fields name in this file too.

Comment (AkshGautam) [reply mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java]: @therajanmaurya  Done.
