### PR TITLE
Fix #990: Adding Reports field and preventing crash

### LINKED ISSUE #990: Adding more Fields in Reports and Preventing Crash
**Summary:** 

Currently, the reports contain insufficient fields as compared to the web app, these fields are dynamic and should be fetched from API. For example, there should be loan officers respective to an office and loan product corresponding to currency etc. Moreover, the app is crashing on clicking the **Run Report** 

**Steps to reproduce:** 

1) Run the app
2) Run reports from the navbar
3) Client Loan listing

**Screenshots:** 
**Web App fields for Loan Listing**
screenshot from 2018-06-09 11-01-08

**Crash Gif and insufficient fields**

### PR DESCRIPTION
**Pull request by AkshGautam**
Fix #990 
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  Please review

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0 @droidchef

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/RunReportsActivity.java [hunk 1]
```diff
@@ -27,35 +30,45 @@ protected void onCreate(@Nullable Bundle savedInstanceState) {
...
+        Spinner spinner = new Spinner(getSupportActionBar().getThemedContext());
 
         ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(this,
                 R.array.array_runreport, R.layout.simple_spinner_item);
         adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
         spinner.setAdapter(adapter);
         spinner.setOnItemSelectedListener(this);
-
         toolbar.addView(spinner);
+        intent = new Intent("report");
```
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/RunReportsActivity.java]: Don't use any Action like this. From the [documentation](https://developer.android.com/reference/android/content/Intent) : 

> Note that the action must be in a namespace because Intents are used globally in the system -- for example the system VIEW action is android.intent.action.VIEW; an application's custom action would be something like com.google.app.myapp.CUSTOM_ACTION

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/reportcategory/ReportCategoryFragment.java [hunk 2]
```diff
@@ -60,6 +74,7 @@ public static ClientReportCategoryFragment newInstance() {
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         ((MifosBaseActivity) getActivity()).getActivityComponent().inject(this);
+        getActivity().registerReceiver(this.broadCastNewMessage, new IntentFilter("report"));
```
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/reportcategory/ReportCategoryFragment.java]: It'll be better to keep this `action` too in the Constants file.

File: mifosng-android/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -245,6 +246,18 @@
     <string name="menu_run_report">Run Report</string>
     <string name="menu_export_csv">Export CSV</string>
     <string name="msg_report_empty">No data retrieved for the chosen report!</string>
+    <string name="report_loan_purpose">"Loan Purpose"</string>
+    <string name="par_calculation">PAR Calculation</string>
+    <string name="savings_acc_deposit">SavingsAccDeposit</string>
+    <string name="glaccount">GLAccountNO</string>
+    <string name="obligation_date_type">Obligation date type</string>
+    <string name="start_date">Start Date</string>
```
Comment (tarun0) [inline mifosng-android/src/main/res/values/strings.xml]: Please verify if these are already not present. There are chances that these may already be used somewhere. Ignore if they are not present earlier.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/reportcategory/ReportCategoryFragment.java (hunk 2 above)
Comment (AkshGautam) [reply mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/reportcategory/ReportCategoryFragment.java]: @tarun0  done

File: mifosng-android/src/main/res/values/strings.xml (hunk 3 above)
Comment (AkshGautam) [reply mifosng-android/src/main/res/values/strings.xml]: @tarun0  verified
