### PR TITLE
fix: sort groups list

### LINKED ISSUE #819: Groups are not in sorted way
Summary:

The groups in group section  from the navigation bar are unsorted manner which makes it complex to search through the particular group during online mode.

Steps to reproduce:

For instance

Run the app
Open Navigation Bar
Select Groups
Expected behavior:

Lexicographically sorted entries for easier lookup.

Observed behavior:

Unsorted entries make search difficult.

Device and Android version:

Android 5.0.2, API 23
screenshot_20180131-143328

### PR DESCRIPTION
**Pull request by laxyapahuja**
Fixes #819 

ezgif-4-bbd6128021f7

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by laxyapahuja** [comment]
@moksh-mahajan @luckyman20 @santoshconflux @elirehema hey, can you please review this task. thanks :D

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java [hunk 1]
```diff
@@ -259,6 +261,12 @@ public void reloadOnError() {
     @Override
     public void showGroups(List<Group> groups) {
         mGroupList = groups;
+        Collections.sort(mGroupList, new Comparator<Group>() {
+            @Override
+            public int compare(Group o1, Group o2) {
```
Comment (luckyman20) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java]: Give Groups a better name.

Comment (laxyapahuja) [reply mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java]: done :D
