### PR TITLE
fix: LoanTermFrequencyType overriding enabled

### LINKED ISSUE #726: Mifosxdroid unable to setup daily loan repayment schedule
While setting up a loan, the Mobile App by default can only set loan repayment schedule to monthly or can be toggled to yearly, so one is unable to make repayment schedule daily except from the community App/server, where modify loan and change the term and repayment frequency to daily.

The mobile Apps needs to have the option of setting up loan for daily repayment.

### PR DESCRIPTION
**Pull request by tarun0**
Fix #726 

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java [hunk 1]
```diff
@@ -718,7 +718,7 @@ private void showHideRepaidMonthSpinners(int visibility) {
 
     private void showDefaultValues() {
         interestRatePerPeriod = mLoanTemplate.getInterestRatePerPeriod();
-        loanTermFrequencyType = mLoanTemplate.getInterestRateFrequencyType().getId();
+        loanTermFrequency = mLoanTemplate.getInterestRateFrequencyType().getId();
```
Comment (therajanmaurya) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java]: @tarun0 default value should be termPeriodFrequencyType id not interestRateFrequencyType id.

Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java]: @therajanmaurya Done
