### PR TITLE
fix: Update identifiers list on adding or removing items

### LINKED ISSUE #658: Identifier item still visible after deleting it
**Summary:** 

When there is only one identifier left and user deletes it we get a message saying "Identifier deleted successfully" but the identifier item is still visible.

**Steps to reproduce:** 

OPen app
Select Clients from Navbar
Select Client with only one identifier
From toolbar menu select Identifiers
Delete the identifier

**Expected behavior:** 

On deleting the identifier the identifier shouldn't be visible .

**Observed behavior:** 

The identifier is still visible on deleting it.

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by tarun0**
Fix #658

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/ClientIdentifierCreationListener.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+/**
+ * Created by Tarun on 07-08-17.
+ */
+
+public interface ClientIdentifierCreationListener {
+
+    void onClientIdentifierCreationSuccess();
+
+    void onClientIdentifierCreationFailure();
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/ClientIdentifierCreationListener.java]: Amazing 😀 That you care about failures and not just success.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java [hunk 2]
```diff
@@ -52,6 +52,8 @@
     @Inject
     IdentifierDialogPresenter mIdentifierDialogPresenter;
 
+    ClientIdentifierCreationListener clientIdentifierCreationListener;
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java]: Can this be ```private``` and also ```@Nullable``` since I see you are doing a null check below.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java [hunk 3]
```diff
@@ -52,6 +52,8 @@
...
+
     View rootView;
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java]: View should be ```private``` even if this is not your change, please do it since we've spotted the problem in this review.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java [hunk 4]
```diff
@@ -130,16 +132,34 @@ public void showUserInterface() {
     public void showClientIdentifiers(List<Identifier> identifiers) {
         this.identifiers = identifiers;
         identifierListAdapter.setIdentifiers(identifiers);
+        identifierListAdapter.notifyDataSetChanged();
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: This is a bad way of handling changes on a recycler view. I'd recommend reading Google's Documentation about RecyclerView. 

Hint : You should almost never call ```notifyDataSetChanged()``` method on a RecyclerView's Adapter. There are other methods available for addition, modification, removal etc. 

Also read about ```DiffUtils``` and try to use that here. 

I am aware we use this bad approach all across the app but this is the time you learn and do it and set a precedence for the future devs so we can just point them to your code and they can learn from it.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java [hunk 5]
```diff
@@ -130,16 +132,34 @@ public void showUserInterface() {
...
     }
 
     @Override
+    public void onClientIdentifierCreationSuccess() {
+        loadIdentifiers();
+    }
+
+    @Override
+    public void onClientIdentifierCreationFailure() {
+
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: This is Nasty !! 😡 An Empty Stub Method pushed sent in a PR that does nothing. WHY is it not implemented ?

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java [hunk 6]
```diff
@@ -130,16 +132,34 @@ public void showUserInterface() {
...
-    public void showEmptyClientIdentifier() {
+    private void showEmptyClientIdentifier() {
         ll_error.setVisibility(View.VISIBLE);
         mNoIdentifierText.setText(getResources().getString(R.string.no_identifier_to_show));
         mNoIdentifierIcon.setImageResource(R.drawable.ic_assignment_turned_in_black_24dp);
     }
 
     @Override
+    public void onClientIdentifierCreationSuccess() {
+        loadIdentifiers();
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: Why do you want to retrieve all the identifiers again, when you create a new Identifier ? You have most of the data already that you ```POST```, you'll get some stuff from the server in the response like ID or whatever that the server is responsible for generating. Why don't you just push that stuff into your list ?

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java [hunk 7]
```diff
@@ -187,4 +195,8 @@ public void onItemSelected(AdapterView<?> parent, View view, int position, long
     public void onNothingSelected(AdapterView<?> parent) {
 
     }
+
+    public void setOnClientIdentifierCreationListener(ClientIdentifierCreationListener listener) {
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java]: ```@Nullable``` annotation missing.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java (hunk 4 above)
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: I read about `DiffUtils` and if I understood it well, it's a good option to juxtapose two lists. In our case, however, we are sure of either 'adding' or 'removing' a single identifier. How about we have a method in the adapter to add (or remove the identifier) and then `dispatchUpdatesTo()` the adapter? Or is `DiffUtils` a better option?

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java (hunk 6 above)
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: Thanks! I never noticed this tbh. Implemented it this way.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java (hunk 4 above)
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: I agree with you ! ```DiffUtils``` is not relevant for our case. However I just wanted to you to know about it :) It is optimized for large operations in our case we won't have very large lists to play with. You can even copy new lists to old ones :P 
However since we know about additions and deletions we can use more precise methods than just ``` notifyDataSetChanged()```

Makes sense ?

Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: Yes. Used `notifyItemInserted(position)` and `notifyItemRemoved(position)` methods now and saved some bandwidth. :P

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java (hunk 5 above)
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java]: Sorry! It was handled in the dialogfragment to. Nevertheless, I edited and implemented in a better way now.

File: mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java [hunk 8]
```diff
@@ -316,10 +317,10 @@ public DataManagerClient(BaseApiManager baseApiManager,
      *
      * @param clientId          Client Id
      * @param identifierPayload IdentifierPayload
-     * @return GenericResponse
+     * @return IdentifierCreationResponse
      */
-    public Observable<GenericResponse> createClientIdentifier(int clientId,
-                                                              IdentifierPayload identifierPayload) {
+    public Observable<IdentifierCreationResponse> createClientIdentifier(
```
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java]: @therajanmaurya We are not fetching the identifiers list again. We are retrieving the created identifier's id from the response based on the discussion with @droidchef  That's why I changed it.

Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java]: @droidchef  Will it be a better approach to check if the `GenericResponse` got `resourceId` and similar values that we want to check and then proceed accordingly? You once told about the naming and readability. I created the new model following those lines.

**Comment by therajanmaurya** [comment]
@tarun0 Please fix the conflicts.
