### PR TITLE
fix: NPE on generating Individual collectionsheet

### LINKED ISSUE #732: App crashes sometimes on retrieving individual collectionsheet
**Summary:** 

App crashes sometimes on retrieving individual collectionsheet.

**Steps to reproduce:** 

Open Individual CollectionSheet in from the Navigational Drawer. Select these values - Head Office, 21 July 2017 and Ch, Sagar and click on Generate. 

**Expected behavior:** 

App should have shown collectionsheet.

**Observed behavior:** 

App crashes.

**Device and Android version:** 

Android 4.2.2 Jellybean.

### PR DESCRIPTION
**Pull request by tarun0**
Fix #732 

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by tarun0** [comment]
@therajanmaurya I've updated the PR as suggested by @droidchef

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/collectionsheetindividual/IndividualCollectionSheetPresenter.java [hunk 1]
```diff
@@ -252,10 +252,12 @@ public void call(PaymentTypeOptions paymentTypeOption) {
                 .subscribe(new Action1<ClientCollectionSheet>() {
                     @Override
                     public void call(ClientCollectionSheet client) {
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/collectionsheetindividual/IndividualCollectionSheetPresenter.java]: Why is the ClientCollectionSheet object called client here ?

File: mifosng-android/src/main/java/com/mifos/objects/collectionsheet/ClientCollectionSheet.java [hunk 2]
```diff
@@ -14,6 +15,7 @@
     private int clientId;
     private String clientName;
 
+    @Nullable
     private ArrayList<LoanCollectionSheet> loans;
```
Comment (droidchef) [inline mifosng-android/src/main/java/com/mifos/objects/collectionsheet/ClientCollectionSheet.java]: Why is the LoanCollectionSheet List called loans here ?

Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/objects/collectionsheet/ClientCollectionSheet.java]: `LoanCollectionSheet` refers to the Loan related to the CollectionSheet. Again, like ClientCollectionSheet, I named this so to discern it from the normal Loans. It's called `loans` as this is the identifier which is received in the JSON response.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/collectionsheetindividual/IndividualCollectionSheetPresenter.java (hunk 1 above)
Comment (tarun0) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/collectionsheetindividual/IndividualCollectionSheetPresenter.java]: `ClientCollectionSheet` object refers to the `Client` specific for CollectionSheet. Since there were already some `Client` models, I named this one which is specific to the CollectionSheet, as `ClientCollectionSheet`.  That's why I named the variable client.

**Comment by tarun0** [comment]
@droidchef I updated the PR with appropriate variable names.

**Comment by therajanmaurya** [comment]
@tarun0 Please fix the conflicts

**Comment by tarun0** [comment]
@therajanmaurya  Fixed.
