### PR TITLE
fixed app crashes when the floating button is clicked in the Group client

### LINKED ISSUE #1941: App crashes when the floating button is clicked in the Group client
**Summary:** 

When clicking the floating button in the Group client, the application crashes

**Steps to reproduce:** 

https://user-images.githubusercontent.com/94394661/230774600-080e46ae-e4a9-4d4d-bae0-b313923b840d.mp4

**Device and Android version:** 

Device : OnePlus Nord
Android 12

### PR DESCRIPTION
**Pull request by Aditya-gupta99**
Fixes #1941 

https://user-images.githubusercontent.com/94394661/231192938-27c152a4-28d7-416d-b60d-f44f18c12ea5.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Aditya-gupta99** [comment]
@avinash14022002 Kindly review this PR.

File: mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.kt [hunk 1]
```diff
@@ -177,8 +177,17 @@ class ClientListFragment : MifosBaseFragment(), ClientListMvpView, OnRefreshList
 
     @OnClick(R.id.fab_create_client)
     fun onClickCreateNewClient() {
-        (activity as MifosBaseActivity?)!!.replaceFragment(CreateNewClientFragment.newInstance(),
+        if(arguments == null)
+        {
+            (activity as MifosBaseActivity?)!!.replaceFragment(CreateNewClientFragment.newInstance(),
```
Comment (avinash14022002) [inline mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.kt:182]: please change with respect to null safety

Comment (avinash14022002) [reply mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.kt]: > please change with respect to null safety

use null safety

**Review by avinash14022002 — APPROVED** [review]

**Review by avinash14022002 — APPROVED** [review]
